simul_name = "bench_scao_sh_16x16_16pix"

[loop]
niter = 1000
ittime = 0.002

[geom]
zenithangle = 0.0
pupdiam = 256

[tel]
diam = 8.0
cobs = 0.12

[atmos]
r0 = 0.15
nscreens = 4
frac = [0.5, 0.2, 0.2, 0.1]
alt = [0.0, 4499.0, 4500.0, 9000.0]
windspeed = [10.0, 20.0, 15.0, 10.0]
winddir = [0.0, 45.0, 90.0, 30.0]
L0 = [25.0, 25.0, 25.0, 25.0]

[[target]]
xpos = 0.0
ypos = 0.0
Lambda = 1.65
mag = 10.0

[[wfs]]
type = "sh"
nxsub = 16
npix = 8
pixsize = 0.3
fracsub = 0.8
xpos = 0.0
ypos = 0.0
Lambda = 0.55
gsmag = 3
optthroughput = 0.5
zerop = 1.0e11
noise = 0
atmos_seen = 1
# lgs parameters
# gsalt = 90*1.e3
# lltx = 0
# llty = 0
# laserpower = 10
# lgsreturnperwatt = 1.e3
# proftype = "Exp"
# beamsize = 0.8

[[dm]]
type = "pzt"
nact = 17
alt = 0.0
thresh = 0.3
coupling = 0.2
unitpervolt = 0.01
push4imat = 100
# influType = "gaussian"
# pattern = "hexa"

# [[dm]]
# type = "tt"
# alt = 0.
# unitpervolt = 0.0005
# push4imat = 10.

[[centroider]]
nwfs = 0
type = "cog"
# type = "corr"
# type_fct = "model"

[[controller]]
type = "generic"
nwfs = [0]
ndm = [0]
maxcond = 1500
delay = 1
gain = 0.4
modopti = false